### ISSUE TITLE
问题求证

### ISSUE THREAD

**Issue by LittleYouEr** [madsys-dev/deepseekv2-profile#1]
https://github.com/madsys-dev/deepseekv2-profile/blob/main/workspace/blog/optimizing-mla.md#projection-absorption 开头描述的这段文字：
> 上述分析和实验结果表明，相比缓存完整的KV Cache，缓存压缩后的KV Cache会带来较大的性能下降。另外一个重要的问题是，当前的CacheDecompressed实现实际上并不能缓解KV Cache过大的问题，这是由于在计算MLA的时候，仍然需要存储解压后的完整的KV Cache，这很可能引起OOM崩溃。

我理解会有点歧义，我理解无论是CD版本还是CC版本，计算过程中都涉及到了解压完整KV后计算qkv attn的操作，所以都有可能OOM。

麻烦作者大佬确认下。

**Comment by wx-csy** [comment]
这是一个笔误，`CacheDecompressed`应为`CacheCompressed`。已修正。
